name = "NeoCobbleverse"
author = "jfzum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb0d0ffd2d3b8b8fd939b8b62955a03f4347f44043974d0ab3ad837de3d85fc0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
