name = "NeoCobbleverse"
author = "jfzum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c91cafba4883b0652c844642f54bf390b2e6ad14f2a33b7250a126f66da9724d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.226"
